### PR TITLE
Ported eslint

### PR DESCRIPTION
**Pull request by dhruvdutt**
@rcodonnell Please check the ported rules. I'll be working with files later once the rules are accepted.
I could not find eslint rules for the following things:
`nonbsp` `noarg`
I believe, we don't need to use `noarg` if we're working in `strict mode`.

### CODE REVIEW

**Comment by rcodonnell** [comment]
Sorry, misunderstood the changes you made

**Comment by dhruvdutt** [comment]
There are 3 eslint configs inside the project. One in root and two more inside `server` and `client` folder each which gets precedence over the root config.
Should I set same rules for all 3 configs?
Also, please add `hacktoberfest` label to this PR if possible.

**Comment by rcodonnell** [comment]
We can't have the exact same config for each because client is es5 and server is es6

**Comment by rcodonnell** [comment]
Build is failing because it is missing required packages for eslint

**Comment by dhruvdutt** [comment]
@rcodonnell Please check the build fail error.

**Pull request merged**
